In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = [10, 20, 30]
b = [40, 50, 60]

In [4]:
type(a)

list

In [5]:
isinstance(a, list)

True

In [6]:
a + b

[10, 20, 30, 40, 50, 60]

In [8]:
x = np.array(a)
y = np.array(b)
type(x)

numpy.ndarray

In [9]:
x

array([10, 20, 30])

In [10]:
y

array([40, 50, 60])

In [11]:
x + y

array([50, 70, 90])

In [12]:
a

[10, 20, 30]

In [13]:
a * 4

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]

In [14]:
"100" * 4

'100100100100'

In [ ]:
x 

array([10, 20, 30])

In [16]:
x * 4

array([ 40,  80, 120])

In [17]:
x

array([10, 20, 30])

In [18]:
x.dtype # data type

dtype('int64')

In [19]:
x.shape

(3,)

In [20]:
t = np.array([[1,2,3], [4,5,6]])
t

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
t.shape

(2, 3)

In [22]:
len(t)

2

In [23]:
np.random.randint(1, 100)

83

In [ ]:
np.random.randint(1, 100, 10)

array([98, 47, 39, 39, 51, 59, 52,  4, 32, 22])

In [35]:
np.random.seed(42)
mat = np.random.randint(1, 100, (3,4))
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [ ]:
mat + 10

array([[ 62, 103,  25,  82],
       [ 71,  31,  93,  97],
       [ 85,  85,  98,  34]])

In [37]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [38]:
mat.reshape(2, 6)

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24]])

In [41]:
mat.reshape(4, 3)

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [42]:
mat.reshape(4, -1)

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [43]:
mat.reshape(6, -1)

array([[52, 93],
       [15, 72],
       [61, 21],
       [83, 87],
       [75, 75],
       [88, 24]])

In [44]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [45]:
mat.max()

93

In [46]:
mat.max(axis=0)

array([75, 93, 88, 87])

In [47]:
mat.max(axis=1)

array([93, 87, 88])

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.ones((3, 4)) * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [55]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [56]:
mat > 50

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False]])

In [57]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [68]:
np.random.seed(43)
mat2 = np.random.randint(1, 100, (3,4))
mat2

array([[69, 65, 50, 22],
       [59, 17, 52, 18],
       [60, 92, 67, 31]])

In [69]:
np.concatenate((mat, mat2), axis=0)

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24],
       [69, 65, 50, 22],
       [59, 17, 52, 18],
       [60, 92, 67, 31]])

In [70]:
np.concatenate((mat, mat2), axis=1)

array([[52, 93, 15, 72, 69, 65, 50, 22],
       [61, 21, 83, 87, 59, 17, 52, 18],
       [75, 75, 88, 24, 60, 92, 67, 31]])

In [65]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [66]:
mat[:2, :3]

array([[52, 93, 15],
       [61, 21, 83]])

In [67]:
mat[:, 2]

array([15, 83, 88])